# Build settings

markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  style: :nested

gems:
 - jekyll-coffeescript

github:
  repo: girlup/girlup.github.io
  branch: master

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

excerpt_separator: "</p>"
timezone: America/New_York
